### ISSUE TITLE
Generating Dialogue Issues

### ISSUE THREAD

**Issue by lsyysl9711** [iwangjian/Color4Dial#1]
Thanks for sharing your codes!

But when I run bash scripts/durecdial_dialog_train.sh. The terminal told me that

![cbbea35da11b573c26a355e219cf871](https://github.com/iwangjian/Color4Dial/assets/71112568/cc6b75d6-9ccb-4ff2-be6e-f83394c62954)

It seems that you add another variable that can not be accepted by the handler.

**Comment by iwangjian** [comment]
Hi, this might be attributed to the version update of `pytorch-ignite`, please use `pytorch-ignite==0.2.1` as listed in `requirements.txt`. Thanks.

**Comment by kremHabashy** [comment]
When I use that version of ignite I get

```
/usr/local/lib/python3.10/dist-packages/transformers/models/bart/modeling_bart.py:549: FutureWarning: The class `PretrainedBartModel` has been depreciated, please use `BartPreTrainedModel` instead.
  warnings.warn(
Traceback (most recent call last):
  File "/content/Color4Dial/main_dialog.py", line 22, in <module>
    from train.trainer_dialog import IgniteTrainer
  File "/content/Color4Dial/train/trainer_dialog.py", line 9, in <module>
    from ignite.engine import Engine, Events
  File "/usr/local/lib/python3.10/dist-packages/ignite/__init__.py", line 1, in <module>
    import ignite.engine
  File "/usr/local/lib/python3.10/dist-packages/ignite/engine/__init__.py", line 3, in <module>
    from ignite.engine.engine import Engine, State, Events
  File "/usr/local/lib/python3.10/dist-packages/ignite/engine/engine.py", line 9, in <module>
    from ignite._utils import _to_hours_mins_secs
  File "/usr/local/lib/python3.10/dist-packages/ignite/_utils.py", line 3, in <module>
    from ignite.utils import convert_tensor, apply_to_tensor, apply_to_type, to_onehot
  File "/usr/local/lib/python3.10/dist-packages/ignite/utils.py", line 4, in <module>
    from torch._six import string_classes
ModuleNotFoundError: No module named 'torch._six'
```

If I upgrade ignite, I get the same error as lsyysl9711

**Comment by iwangjian** [comment]
Hi, this might be because your Pytorch version >=2.0. Please downgrade the version of Pytorch to >=1.10 but < 2.0.

**Comment by kremHabashy** [comment]
I have torch-1.12.0

**Comment by kremHabashy** [comment]
Resolved by using python 3.8.
